# Generated by Django 5.1.2 on 2024-10-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='company_logos/')),
                ('image', models.ImageField(upload_to='company_images/')),
                ('heading', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('location', models.CharField(max_length=255)),
                ('site', models.URLField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
